# Download List of indicators

## 1. Set up ypur credential in a dictionay

In [52]:
token = '0da8814e96d763b9cf7064c7bac636d7ef9a8e584ec2daf14d76046094c9131c'

headers = dict()
headers ['Host'] = 'api.esios.ree.es'
headers['x-api-key'] = token

In [53]:
headers

{'Host': 'api.esios.ree.es',
 'x-api-key': '0da8814e96d763b9cf7064c7bac636d7ef9a8e584ec2daf14d76046094c9131c'}

## 2.Request the indicators list

In [54]:
url ='https://api.esios.ree.es/indicators'

In [55]:
# %pip install requests
import requests

In [56]:
res=requests.get(url, headers=headers)

In [57]:
res.__dict__

{'_content': b'{\n  "indicators": [\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Hidr\xc3\xa1ulica UGH",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n hidr\xc3\xa1ulica UGH.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Hidr\xc3\xa1ulica UGH",\n      "id": 1\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Hidr\xc3\xa1ulica no UGH",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n hidr\xc3\xa1ulica no UGH.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Hidr\xc3\xa1ulica no UGH",\n      "id": 2\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Turbinaci\xc3\xb3n bombeo",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n turbinaci\xc3\xb3n bombeo.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Turbinaci\xc3\xb3n bombeo",\n      "id": 3\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Nuclear",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n nuclear.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Nuclear",\n      "id": 4\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Hulla antracita Anexo II RD 134/2010",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n Hulla antracita Anexo II RD 134/2010.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Hulla antracita RD 134/2010",\n      "id": 5\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Hulla sub-bituminosa Anexo II RD 134/2010",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n Hulla sub-bituminosa Anexo II RD 134/2010.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Hulla sub-bituminosa RD 134/2010",\n      "id": 6\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Hulla antracita",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n Hulla antracita.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Hulla antracita",\n      "id": 7\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Hulla sub-bituminosa",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n Hulla sub-bituminosa.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Hulla sub-bituminosa",\n      "id": 8\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Ciclo combinado",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n ciclo combinado.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Ciclo combinado",\n      "id": 9\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Fuel",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n fuel.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Fuel",\n      "id": 10\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Gas Natural - Turbina de vapor",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n gas natural.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Turbina de vapor",\n      "id": 11\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF E\xc3\xb3lica terrestre",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n e\xc3\xb3lica terrestre.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "E\xc3\xb3lica terrestre",\n      "id": 12\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF E\xc3\xb3lica marina",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n e\xc3\xb3lica marina.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "E\xc3\xb3lica marina",\n      "id": 13\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Solar fotovoltaica",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n solar fotovoltaica.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Solar fotovoltaica",\n      "id": 14\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Solar t\xc3\xa9rmica",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n solar t\xc3\xa9rmica.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a la ejecuci\xc3\xb3n de contratos bilaterales con entrega f\xc3\xadsica de los cuales se ha confirmado la ejecuci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003e\\u003cb\\u003ePublicaci\xc3\xb3n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\xc3\xb3n del d\xc3\xada D+1.\\u003c/p\\u003e",\n      "short_name": "Solar t\xc3\xa9rmica",\n      "id": 15\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Oc\xc3\xa9ano y geot\xc3\xa9rmica",\n      "description": "\\u003cp\\u003eEs el programa de energ\\u0026iacute;a diario, con desglose horario, de las diferentes Unidades de Programaci\\u0026oacute;n correspondientes a ventas y adquisiciones de energ\\u0026iacute;a en el sistema el\\u0026eacute;ctrico peninsular espa\\u0026ntilde;ol. En concreto este indicador se refiere a las unidades de programaci\\u0026oacute;n con tipo de producci\\u0026oacute;n oc\\u0026eacute;ano y geot\\u0026eacute;rmica.\\u003c/p\\u003e\\r\\n\\r\\n\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\\u0026oacute;n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\\u0026oacute;n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\\u0026oacute;n, incluyendo las correspondientes a la ejecuci\\u0026oacute;n de contratos bilaterales con entrega f\\u0026iacute;sica de los cuales se ha confirmado la ejecuci\\u0026oacute;n.\\u003c/p\\u003e\\r\\n\\r\\n\\u003cp\\u003e\\u003cb\\u003ePublicaci\\u0026oacute;n:\\u003c/b\\u003e diariamente a partir de las 13:45 horas con la informaci\\u0026oacute;n del d\\u0026iacute;a D+1.\\u003c/p\\u003e\\r\\n",\n      "short_name": "Oc\xc3\xa9ano y geot\xc3\xa9rmica",\n      "id": 16\n    },\n    {\n      "name": "Generaci\xc3\xb3n programada PBF Gas Natural Cogeneraci\xc3\xb3n",\n      "description": "\\u003cp\\u003eEs el programa de energ\xc3\xada diario, con desglose horario, de las diferentes Unidades de Programaci\xc3\xb3n correspondientes a ventas y adquisiciones de energ\xc3\xada en el sistema el\xc3\xa9ctrico peninsular espa\xc3\xb1ol. En concreto este indicador se refiere a las unidades de programaci\xc3\xb3n con tipo de producci\xc3\xb3n gas natural cogeneraci\xc3\xb3n.\\u003c/p\\u003e\\u003cp\\u003eEste programa es establecido por el OS a partir de la casaci\xc3\xb3n del OM y de las nominaciones de programas de todas y cada una de las Unidades de Programaci\xc3\xb3n que le han sido comunicadas por los sujetos titulares de dichas Unidades de Programaci\xc3\xb3n, incluyendo las correspondientes a 

In [58]:
res.status_code

200

In [59]:
data = res.json()

type(data)

dict

In [60]:
data.keys()

dict_keys(['indicators', 'meta'])

In [61]:
import pandas as pd

df_indicators = pd.DataFrame(data["indicators"])
df_indicators.head()

,name,description,short_name,id
0,Generación programada PBF Hidráulica UGH,"<p>Es el programa de energía diario, con desgl...",Hidráulica UGH,1
1,Generación programada PBF Hidráulica no UGH,"<p>Es el programa de energía diario, con desgl...",Hidráulica no UGH,2
2,Generación programada PBF Turbinación bombeo,"<p>Es el programa de energía diario, con desgl...",Turbinación bombeo,3
3,Generación programada PBF Nuclear,"<p>Es el programa de energía diario, con desgl...",Nuclear,4
4,Generación programada PBF Hulla antracita Anex...,"<p>Es el programa de energía diario, con desgl...",Hulla antracita RD 134/2010,5

In [62]:
df_indicators.columns

Index(['name', 'description', 'short_name', 'id'], dtype='object')

In [63]:
df_indicators[["id", "name", "short_name", "description"]].head(20)

,id,name,short_name,description
0,1,Generación programada PBF Hidráulica UGH,Hidráulica UGH,"<p>Es el programa de energía diario, con desgl..."
1,2,Generación programada PBF Hidráulica no UGH,Hidráulica no UGH,"<p>Es el programa de energía diario, con desgl..."
2,3,Generación programada PBF Turbinación bombeo,Turbinación bombeo,"<p>Es el programa de energía diario, con desgl..."
3,4,Generación programada PBF Nuclear,Nuclear,"<p>Es el programa de energía diario, con desgl..."
4,5,Generación programada PBF Hulla antracita Anex...,Hulla antracita RD 134/2010,"<p>Es el programa de energía diario, con desgl..."
5,6,Generación programada PBF Hulla sub-bituminosa...,Hulla sub-bituminosa RD 134/2010,"<p>Es el programa de energía diario, con desgl..."
6,7,Generación programada PBF Hulla antracita,Hulla antracita,"<p>Es el programa de energía diario, con desgl..."
7,8,Generación programada PBF Hulla sub-bituminosa,Hulla sub-bituminosa,"<p>Es el programa de energía diario, con desgl..."
8,9,Generación programada PBF Ciclo combinado,Ciclo combinado,"<p>Es el programa de energía diario, con desgl..."
9,10,Generación programada PBF Fuel,Fuel,"<p>Es el programa de energía diario, con desgl..."
10,11,Generación programada PBF Gas Natural - Turbin...,Turbina de vapor,"<p>Es el programa de energía diario, con desgl..."
11,12,Generación programada PBF Eólica terrestre,Eólica terrestre,"<p>Es el programa de energía diario, con desgl..."
12,13,Generación programada PBF Eólica marina,Eólica marina,"<p>Es el programa de energía diario, con desgl..."
13,14,Generación programada PBF Solar fotovoltaica,Solar fotovoltaica,"<p>Es el programa de energía diario, con desgl..."
14,15,Generación programada PBF Solar térmica,Solar térmica,"<p>Es el programa de energía diario, con desgl..."
15,16,Generación programada PBF Océano y geotérmica,Océano y geotérmica,"<p>Es el programa de energ&iacute;a diario, co..."
16,17,Generación programada PBF Gas Natural Cogenera...,Gas Natural Cogeneración,"<p>Es el programa de energía diario, con desgl..."
17,18,Generación programada PBF Derivados del petról...,Derivados del petróleo ó carbón,"<p>Es el programa de energía diario, con desgl..."
18,19,Generación programada PBF Subproductos minería,Subproductos minería,"<p>Es el programa de energía diario, con desgl..."
19,20,Generación programada PBF Energía residual,Energía residual,"<p>Es el programa de energía diario, con desgl..."

## 3.get the JSON

In [66]:
data = res.json()

## 4.Create a `Dataframe`

In [69]:
df_indicators = pd.DataFrame(data['indicators'])

### 4.1 Set the `id` column as the index

In [70]:
df_indicators = df_indicators.set_index('id')

### 4.2. Save the *styled* `DataFrame` to a new variable

In [71]:
df_indicators_styled = df_indicators.style

### 4.3 Export the `DataFrame` to an Excel

In [72]:
df_indicators_styled.to_excel('indicators.xlsx')